"""
utils/pdf_generator.py — Professional PDF Report Generator
Uses ReportLab to produce a styled, multi-section report
"""

import io
import pandas as pd
from datetime import datetime
from typing import Optional

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, PageBreak, KeepTogether,
)
from reportlab.platypus import Image as RLImage

try:
    from utils.chart_engine import suggest_charts, render_chart_as_image
    CHARTS_AVAILABLE = True
except ImportError:
    CHARTS_AVAILABLE = False


# ── Color Palette ─────────────────────────────────────────────────────────────
PRIMARY   = colors.HexColor("#1a73e8")
SECONDARY = colors.HexColor("#34a853")
ACCENT    = colors.HexColor("#fbbc04")
DARK      = colors.HexColor("#202124")
LIGHT_BG  = colors.HexColor("#f8f9fa")
BORDER    = colors.HexColor("#dadce0")


# ── Main Generator ────────────────────────────────────────────────────────────

def generate_pdf_report(
    df: pd.DataFrame,
    title: str,
    author: str,
    university: str,
    filename: str,
    include_stats: bool = True,
    include_charts: bool = True,
    include_missing: bool = True,
    ai_insights: Optional[str] = None,
) -> bytes:
    """
    Generate a complete PDF report and return as bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        rightMargin=2*cm, leftMargin=2*cm,
        topMargin=2*cm, bottomMargin=2*cm,
        title=title,
        author=author,
    )

    styles = _build_styles()
    story  = []

    # ── Cover Page ────────────────────────────────────────────────────────────
    story += _cover_page(title, author, university, filename, styles)
    story.append(PageBreak())

    # ── Table of Contents (static) ────────────────────────────────────────────
    story += _toc(include_stats, include_charts, include_missing, ai_insights, styles)
    story.append(PageBreak())

    # ── Section 1: Dataset Overview ───────────────────────────────────────────
    story += _section_dataset_overview(df, filename, styles)

    # ── Section 2: Missing Values ─────────────────────────────────────────────
    if include_missing:
        story += _section_missing_values(df, styles)

    # ── Section 3: Descriptive Statistics ────────────────────────────────────
    if include_stats:
        story += _section_statistics(df, styles)

    # ── Section 4: Charts ─────────────────────────────────────────────────────
    if include_charts and CHARTS_AVAILABLE:
        story += _section_charts(df, styles)

    # ── Section 5: AI Insights ────────────────────────────────────────────────
    if ai_insights:
        story += _section_ai_insights(ai_insights, styles)

    # ── Footer note ───────────────────────────────────────────────────────────
    story.append(Spacer(1, 1*cm))
    story.append(HRFlowable(width="100%", color=BORDER))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(
        f"Generated by AI Powered Automated Data Analyst System · {datetime.now().strftime('%B %d, %Y')} · University of Sindh, Jamshoro",
        styles["footer"]
    ))

    doc.build(story)
    return buf.getvalue()


# ── Style Builder ─────────────────────────────────────────────────────────────

def _build_styles():
    base = getSampleStyleSheet()
    styles = {}

    styles["cover_title"] = ParagraphStyle(
        "cover_title", parent=base["Title"],
        fontSize=24, textColor=PRIMARY, alignment=TA_CENTER,
        spaceAfter=12, leading=30,
    )
    styles["cover_sub"] = ParagraphStyle(
        "cover_sub", parent=base["Normal"],
        fontSize=12, textColor=DARK, alignment=TA_CENTER, spaceAfter=6,
    )
    styles["section_h"] = ParagraphStyle(
        "section_h", parent=base["Heading1"],
        fontSize=14, textColor=PRIMARY, spaceBefore=18, spaceAfter=8,
        borderPad=4,
    )
    styles["subsection_h"] = ParagraphStyle(
        "subsection_h", parent=base["Heading2"],
        fontSize=11, textColor=SECONDARY, spaceBefore=10, spaceAfter=4,
    )
    styles["body"] = ParagraphStyle(
        "body", parent=base["Normal"],
        fontSize=10, textColor=DARK, spaceAfter=4, leading=14,
        alignment=TA_JUSTIFY,
    )
    styles["caption"] = ParagraphStyle(
        "caption", parent=base["Normal"],
        fontSize=8, textColor=colors.grey, alignment=TA_CENTER, spaceAfter=8,
    )
    styles["footer"] = ParagraphStyle(
        "footer", parent=base["Normal"],
        fontSize=8, textColor=colors.grey, alignment=TA_CENTER,
    )
    styles["bullet"] = ParagraphStyle(
        "bullet", parent=base["Normal"],
        fontSize=10, textColor=DARK, leftIndent=15, spaceAfter=3,
        bulletIndent=5,
    )
    styles["toc_item"] = ParagraphStyle(
        "toc_item", parent=base["Normal"],
        fontSize=11, textColor=DARK, spaceAfter=6, leftIndent=20,
    )
    return styles


# ── Page Sections ─────────────────────────────────────────────────────────────

def _cover_page(title, author, university, filename, styles):
    els = []
    els.append(Spacer(1, 3*cm))
    els.append(Paragraph("🤖", ParagraphStyle("icon", fontSize=40, alignment=TA_CENTER)))
    els.append(Spacer(1, 0.5*cm))
    els.append(Paragraph(title, styles["cover_title"]))
    els.append(Spacer(1, 0.5*cm))
    els.append(HRFlowable(width="80%", color=PRIMARY, thickness=2))
    els.append(Spacer(1, 0.5*cm))
    els.append(Paragraph(f"Dataset: <b>{filename}</b>", styles["cover_sub"]))
    els.append(Paragraph(f"Prepared by: <b>{author}</b>", styles["cover_sub"]))
    els.append(Paragraph(university, styles["cover_sub"]))
    els.append(Spacer(1, 0.3*cm))
    els.append(Paragraph(
        f"Generated on: {datetime.now().strftime('%B %d, %Y at %H:%M')}",
        styles["cover_sub"]
    ))
    els.append(Spacer(1, 2*cm))
    els.append(Paragraph(
        "AI Powered Automated Data Analyst System — Final Year Project 2026",
        ParagraphStyle("tagline", fontSize=9, textColor=colors.grey, alignment=TA_CENTER)
    ))
    return els


def _toc(include_stats, include_charts, include_missing, ai_insights, styles):
    els = []
    els.append(Paragraph("Table of Contents", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.3*cm))

    sections = [
        "1. Dataset Overview",
        "2. Missing Values Analysis" if include_missing else None,
        "3. Descriptive Statistics" if include_stats else None,
        "4. Auto-Generated Charts" if include_charts else None,
        "5. AI Insights & Analysis" if ai_insights else None,
    ]
    for s in sections:
        if s:
            els.append(Paragraph(s, styles["toc_item"]))
    return els


def _section_dataset_overview(df, filename, styles):
    els = []
    els.append(Paragraph("1. Dataset Overview", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.2*cm))

    num_cols  = df.select_dtypes("number").columns.tolist()
    cat_cols  = df.select_dtypes(include=["object", "category"]).columns.tolist()
    date_cols = df.select_dtypes(include=["datetime"]).columns.tolist()

    info = [
        ["Metric", "Value"],
        ["File Name",            filename],
        ["Total Rows",           f"{len(df):,}"],
        ["Total Columns",        str(len(df.columns))],
        ["Numeric Columns",      str(len(num_cols))],
        ["Categorical Columns",  str(len(cat_cols))],
        ["Date/Time Columns",    str(len(date_cols))],
        ["Total Missing Values", str(int(df.isnull().sum().sum()))],
        ["Duplicate Rows",       str(int(df.duplicated().sum()))],
    ]
    t = Table(info, colWidths=[6*cm, 10*cm])
    t.setStyle(_info_table_style())
    els.append(t)
    els.append(Spacer(1, 0.5*cm))

    # Column list
    els.append(Paragraph("Column Names:", styles["subsection_h"]))
    col_str = ", ".join(df.columns.tolist())
    els.append(Paragraph(col_str, styles["body"]))
    els.append(Spacer(1, 0.5*cm))
    return els


def _section_missing_values(df, styles):
    els = []
    els.append(Paragraph("2. Missing Values Analysis", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.2*cm))

    missing = df.isnull().sum()
    missing_pct = (missing / len(df) * 100).round(2)
    missing_df = pd.DataFrame({
        "Column": missing.index,
        "Missing Count": missing.values,
        "Missing %": missing_pct.values,
    }).query("`Missing Count` >= 0").sort_values("Missing Count", ascending=False)

    table_data = [["Column", "Missing Count", "Missing %"]]
    for _, row in missing_df.iterrows():
        table_data.append([row["Column"], str(row["Missing Count"]), f"{row['Missing %']}%"])

    t = Table(table_data, colWidths=[8*cm, 5*cm, 4*cm])
    t.setStyle(_data_table_style())
    els.append(t)
    els.append(Spacer(1, 0.5*cm))
    return els


def _section_statistics(df, styles):
    els = []
    els.append(Paragraph("3. Descriptive Statistics", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.2*cm))

    num_cols = df.select_dtypes("number").columns.tolist()
    if not num_cols:
        els.append(Paragraph("No numeric columns found.", styles["body"]))
        return els

    desc = df[num_cols].describe().T.round(3)
    desc.reset_index(inplace=True)
    desc.rename(columns={"index": "Column"}, inplace=True)

    headers = desc.columns.tolist()
    table_data = [headers]
    for _, row in desc.iterrows():
        table_data.append([str(v) for v in row.values])

    col_w = [3.5*cm] + [2*cm] * (len(headers) - 1)
    t = Table(table_data, colWidths=col_w)
    t.setStyle(_data_table_style())
    els.append(t)
    els.append(Spacer(1, 0.5*cm))
    return els


def _section_charts(df, styles):
    from utils.chart_engine import suggest_charts, render_chart_as_image
    els = []
    els.append(Paragraph("4. Auto-Generated Charts", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.2*cm))

    suggestions = suggest_charts(df)[:4]    # embed up to 4 charts

    if not suggestions:
        els.append(Paragraph("No suitable charts could be generated for this dataset.", styles["body"]))
        return els

    for spec in suggestions:
        img_bytes = render_chart_as_image(df, spec)
        if img_bytes:
            img_buf = io.BytesIO(img_bytes)
            img = RLImage(img_buf, width=15*cm, height=8*cm)
            els.append(KeepTogether([
                img,
                Paragraph(spec["title"], styles["caption"]),
                Spacer(1, 0.5*cm),
            ]))

    return els


def _section_ai_insights(insights_text, styles):
    els = []
    els.append(Paragraph("5. AI Insights & Analysis", styles["section_h"]))
    els.append(HRFlowable(width="100%", color=BORDER))
    els.append(Spacer(1, 0.2*cm))

    # Parse markdown-ish text into paragraphs
    for line in insights_text.split("\n"):
        line = line.strip()
        if not line:
            els.append(Spacer(1, 0.15*cm))
        elif line.startswith("## "):
            els.append(Paragraph(line[3:], styles["subsection_h"]))
        elif line.startswith("# "):
            els.append(Paragraph(line[2:], styles["subsection_h"]))
        elif line.startswith("- ") or line.startswith("• "):
            els.append(Paragraph(f"• {line[2:]}", styles["bullet"]))
        elif line.startswith("**") and line.endswith("**"):
            els.append(Paragraph(f"<b>{line[2:-2]}</b>", styles["body"]))
        else:
            # Replace inline bold
            line = line.replace("**", "<b>", 1).replace("**", "</b>", 1)
            els.append(Paragraph(line, styles["body"]))

    els.append(Spacer(1, 0.5*cm))
    return els


# ── Table Styles ──────────────────────────────────────────────────────────────

def _info_table_style():
    return TableStyle([
        ("BACKGROUND",  (0, 0), (-1, 0), PRIMARY),
        ("TEXTCOLOR",   (0, 0), (-1, 0), colors.white),
        ("FONTNAME",    (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",    (0, 0), (-1, 0), 10),
        ("BACKGROUND",  (0, 1), (-1, -1), LIGHT_BG),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID",        (0, 0), (-1, -1), 0.5, BORDER),
        ("FONTSIZE",    (0, 1), (-1, -1), 9),
        ("TOPPADDING",  (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
    ])


def _data_table_style():
    return TableStyle([
        ("BACKGROUND",    (0, 0), (-1, 0), SECONDARY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), colors.white),
        ("FONTNAME",      (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",      (0, 0), (-1, 0), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, LIGHT_BG]),
        ("GRID",          (0, 0), (-1, -1), 0.4, BORDER),
        ("FONTSIZE",      (0, 1), (-1, -1), 8),
        ("TOPPADDING",    (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING",   (0, 0), (-1, -1), 6),
    ])
